### ISSUE TITLE
Where is ember-template-compiler-1.10.0.js??

### ISSUE THREAD

**Issue by kaluosi** [emberjs/starter-kit#64]
Where is the eember-template-compiler-1.10.0.js file that index.html tries to include in line 26:

<script src="js/libs/ember-template-compiler-1.10.0.js"></script>

¿Is this the reason the starter-kit doesn't work at all?

**Comment by cki** [comment]
I had the same problem. I suggest you do the following:

cd js/libs
wget -O ember-template-compiler-1.10.0.js http://builds.emberjs.com/tags/v1.11.0/ember-template-compiler.js

This way you can use the code in the current master branch (v1.11.0)

**Comment by rwjblue** [comment]
Sorry about that!! Fixed in https://github.com/emberjs/starter-kit/commit/47ac9703914137b9b808b589af941df02765de28.

**Comment by kaluosi** [comment]
Thank you!! It seems ember begins to use ember-cli to create an 
application skeleton but the several ember books doesn't reflect it.
I have copied the ember-template-compiler.js from this skeleton. Now 
let's try again. cc
